---
title: "Julien Bisconti"
baseURL: "https://bisconti.cloud/"
theme: ["zen", "reveal-hugo"]
languageCode: "en-GB"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
author:
  name: "Julien Bisconti"
  url: "https://bisconti.cloud"
  avatar: "/static/images/julien.png"

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true
  Reveal:
    baseName: "index"
    mediaType: "text/html"
    isHTML: true

markup:
  goldmark:
    renderer:
      unsafe: true  # Used for revealjs slides in HTML

outputs:
  home: ["HTML","RSS", "JSON", "SearchIndex"]
  section: ["HTML","RSS", "JSON"]

params:
  mainSections: ["posts", "slides", "talks"]
  contact: "julien@bisconti.cloud"
  copyright: ""
  description: "Julien Bisconti, Freelance Software Engineer Specialized in Google Cloud, living in Stockholm, Swedem, known for slides presentations and conference talks about kubernetes, serverless, GCP, data engineering, logging, monitoring, software architecture"
  dateformat: "2 Jan, 2006"
  favicon: "apple-touch-icon.png"
  feedlinks: true
  footer: "Powered by [Hugo](https://gohugo.io/), [Zen theme](https://github.com/frjo/hugo-theme-zen) and [reveal-hugo](https://github.com/dzello/reveal-hugo), hosted on [Netlify](https://www.netlify.com/)"
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  imageMaxWidth: 400
  mobileMenu: true
  poweredby: false
  sidebar: false
  social_links:
    twitter: "julienBisconti"
    github: "veggiemonk"
    linkedin: "julienbisconti"
    web: "https://developers.google.com/community/experts/directory/profile/profile-julien_bisconti"
  submitted: true
  searchfrom: true
  reveal_hugo:
    theme: "moon"

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: false
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: true
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true
